### ISSUE TITLE
Systematic tagging of new releases and upload to PyPI

### ISSUE THREAD

**Issue by ghisvail** [PacificBiosciences/pbcore#110]
Please consider systematically tagging and releasing tarballs to PyPI in the future. Neither 1.2.11, 1.2.12, 1.3.0 and now 1.4.0 were tagged nor pushed to PyPI which makes tracking of new releases downstream more difficult than it should be. Right now, anything requiring pbcore would still download the outdated 1.2.10 version from PyPI.

Thanks,

**Comment by pb-dseifert** [comment]
For legal reasons we dont upload releases to PyPI anymore. If you'd like to use pbcore, please use it via Bioconda.
