### ISSUE TITLE
InvalidDataSetIOError

### ISSUE THREAD

**Issue by linz-li** [PacificBiosciences/pbcore#112]
when I run arrow, I got a arrow
`InvalidDataSetIOError: No reference tables found, are these input files aligned?`
my command is `arrow  -j8  --referenceFilename  contig.fasta  -o arrow.fasta   subreads.bam`
what's wrong?

**Comment by mdsmith** [comment]
Hi linz-li, is your subreads.bam file aligned? Arrow can only take aligned bam files as input, and we typically use "subreads.bam" to refer to a file of unaligned subreads.

**Comment by linz-li** [comment]
Yeah,I got the bam with bax2bam. But if I was run, how to produce the aligned bam file. With bwa or bowtie2?It's time consuming！

**Comment by mdsmith** [comment]
To be compatible with arrow, alignment must be performed with pbalign: https://github.com/PacificBiosciences/pbalign. It is also tuned for PacBio data.

**Comment by linz-li** [comment]
thank you！I didn't  know pbalign can also produce bam format except cmp.h5 format. I'all try it!
