### ISSUE TITLE
SMART Analysis - QUIVER - pbtranscript.py   ", line 35, in <module>     from pbcore.util.ToolRunner import PBMultiToolRunner

### ISSUE THREAD

**Issue by uqvirg** [PacificBiosciences/pbcore#113]
Hi,
I want to run ICE and Quiver with Command-line : pbtranscript.py cluster 
I have installed smrt_analysis, the installation was successful.

But when I run:
pbtranscript.py cluster isoseq_flnc.fasta final.consensus.fa \
  --nfl_fa isoseq_nfl.fasta -d cluster --ccs_fofn /reads_of_insert.fofn \
  --bas_fofn input.fofn --cDNA_size under1k --quiver --use_sge \
   --max_sge_jobs 40 --unique_id 300 --blasr_nproc 24 --quiver_nproc 8

I have this error:
Traceback (most recent call last):
  File "./pbtranscript.py", line 35, in <module>
    from pbcore.util.ToolRunner import PBMultiToolRunner

I stuck, I don't know what to do.
Cheers,
Virginie

**Comment by uqvirg** [comment]
To FIX this issue I did
PYTHONPATH=/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/lib/python2.7/
but not sure is very clean !
Traceback (most recent call last):
  File "/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/lib/python2.7/pbtools/pbtranscript/pbtranscript.py", line 37, in <module>
    from pbtools.pbtranscript.Classifier import Classifier, ChimeraDetectionOptions
  File "/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/lib/python2.7/pbtools/pbtranscript/Classifier.py", line 463
    with FastaReader(in_read_fn) as reader, \
                                          ^
SyntaxError: invalid syntax

**Comment by mhsieh** [comment]
are you trying to run analysis/bin/pbtranscript.py directly? A better way is to do 
`/smrtanalysis/smrtcmds/bin/smrtwrap pbtranscript.py` , you don't need PYTHONPATH for that.

**Comment by mhsieh** [comment]
By the way this question should be asked in pbtranscript project.

**Comment by uqvirg** [comment]
Thank you very much !!! Exactly that !
