### ISSUE TITLE
Please use proper release tags

### ISSUE THREAD

**Issue by tillea** [PacificBiosciences/pbcore#116]
Hi,
the release tags are mentioning version 1.2.10 as latest release.  When checking setup.py it specifies version 1.5.0.  It would be really helpful if you could keep the release tags in sync with your release versions.
Thanks a lot, Andreas.

**Comment by pb-dseifert** [comment]
current py3 use proper tags

**Comment by mr-c** [comment]
Thank you @pb-dseifert !

**Comment by tillea** [comment]
On Thu, Jun 04, 2020 at 02:56:49AM -0700, Michael R. Crusoe wrote:
> Thank you @pb-dseifert !

Will you care for the according upload?

Kind regards

     Andreas.

-- 
http://fam-tille.de
