### ISSUE TITLE
inputs to genomicconsensus with arrow algorithm

### ISSUE THREAD

**Issue by peritob** [PacificBiosciences/pbcore#118]
I have assembled a de novo genome (1.98 Gb) with canu v1.6 using pacbio reads. I am in the polish stage and have aligned raw subreads.bam to the assembly with blasr in batches, as the process was running out of allocated walltime when all reads submitted. I therefore have 6 large alignment.bam files 342G, 284G, 240G, 117G, 154G, 78G.

I was trying to merge the bam files using pbmerge, however this too was a very long process and at one stage failed. Is it possible to run these individual alignment.bam files as inputs with the arrow algorithm and get 6 fasta outputs? My thinking is that these are going to be much smaller files to merge but I am not sure if this is valid.

**Comment by pb-dseifert** [comment]
genomicconsensus is dead and EOL. Please use `pbgcpp` in Bioconda as replacement.
