### ISSUE TITLE
Please port to Python3

### ISSUE THREAD

**Issue by tillea** [PacificBiosciences/pbcore#121]
Hello,
the Debian Med team is maintaining pbcore for official Debian. The recently released Debian 10 was the last Debian release featuring Python2 since this programming language is EOL. If you are interested that we continue to maintain pbcore in official Debian (and that users of other modern distributions will have no problems to install pbcore on their systems) I'd recommend you port your code to Python3. The 2to3 tool might be of great help here.
Kind regards, Andreas.

**Comment by armintoepfer** [comment]
Hi!

It's on our radar.

 Armin

**Comment by tillea** [comment]
On Wed, Sep 04, 2019 at 03:05:27AM -0700, Armin Töpfer wrote:
> It's on our radar.
Thanks a lot for the quick response.  Is there any rough time frame for
the port?  From a Debian perspective its not really urgent until our
next release.  Its just good to know how to schedule things.
Kind regards, Andreas.

**Comment by armintoepfer** [comment]
When is the next Debian release timed?

I'm not allowed to share _any_ timelines. This has nothing to do with you ;) 

 Armin

**Comment by tillea** [comment]
On Wed, Sep 04, 2019 at 04:03:20AM -0700, Armin Töpfer wrote:
> When is the next Debian release timed?
When its ready. :-P  I guess somewhen in 2021.
 
> I'm not allowed to share _any_ timelines. This has nothing to do with you ;) 
OK, thanks for the info anyway, Andreas.

**Comment by pb-dseifert** [comment]
Py3 is done now, unfortunately we aren't fully Py 3.8 clean due to the pyxb dependency in #122
