### ISSUE TITLE
pyxb no longer supported upstream

### ISSUE THREAD

**Issue by smoe** [PacificBiosciences/pbcore#122]
Hello,
https://github.com/pabigot/pyxb/issues/100 seeks a new maintainer.  Linux distributions have since started to remove it (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=946602). pbcore uses it (https://github.com/PacificBiosciences/pbcore/blob/1fc62fc14c8f38731012261041977d7a5e1c26da/setup.py#L13) for validations if I get this right.
What should happen now? The best possible answer would possibly be that Pacific Biosciences starts maintaining that package or fund someone else maintaining it. What should us users do in the meantime?
Cheers,
Steffen

**Comment by pb-dseifert** [comment]
You have a point. We'll investigate and see which alternatives work for us. Any recommendations? The other popular ones I know are `lxml` and `xmlschema`.

**Comment by smoe** [comment]
Thank you for your swift reply. lxml is a wrapper for the libxml2 library, which seems like something I personally could understand. And there is a Debian package for it with a steady increase of users (https://qa.debian.org/popcon.php?package=lxml). I am blank about xmlschema or other alternatives, I am afraid.
