### ISSUE TITLE
Read group string with barcode attached cannot be converted to int.

### ISSUE THREAD

**Issue by MatthiasLienhard** [PacificBiosciences/pbcore#123]
I my latest isoseq data, the read group string got the bar code attached (such as in "fca17910/0--1") resulting in an ValueError: invalid literal for int() with base 16: 'fca17910/0--1'
https://github.com/PacificBiosciences/pbcore/blob/63c854bf283b8f50e638073a52a08ed5ba8ebf07/pbcore/io/align/_BamSupport.py#L65

**Comment by natechols** [comment]
Please update your pbcore install, we fixed this a while ago.
