### ISSUE TITLE
"only PacBio BAM files version >= 3.0b3 are supported"

### ISSUE THREAD

**Issue by roncanepa** [PacificBiosciences/pbcore#13]
Hello, I've tried to use the pbcore to read an aligned reads BAM file from smrtportal after an HGAP assembly, but receive the error: `pbcore.io.align._BamSupport.IncompatibleFile: This BAM file is incompatible with this API (only PacBio BAM files version >= 3.0b3 are supported`

It seems to me that this should Just Work, so I'm wondering if I'm missing something.

1. smrtanalysis_2.3.0.140936.p2.144836
1. HGAP assembly finishes
1. download the Aligned Reads *.bam and *.bai files
1.  try to do a simple open with the following script
1. get error message

```
import pbcore.io

with pbcore.io.BamReader("016496_data_aligned_reads.bam"):
    pass

```

```
Traceback (most recent call last):
  File "read-bam.py", line 3, in <module>
    with pbcore.io.BamReader("016496_data_aligned_reads.bam"):
  File "/Users/agnor/.virtualenvs/tmp-5cfd6e743e152dc4/lib/python2.7/site-packages/pbcore-1.0.0-py2.7.egg/pbcore/io/align/BamIO.py", line 308, in __init__
    super(BamReader, self).__init__(fname, referenceFastaFname)
  File "/Users/agnor/.virtualenvs/tmp-5cfd6e743e152dc4/lib/python2.7/site-packages/pbcore-1.0.0-py2.7.egg/pbcore/io/align/BamIO.py", line 166, in __init__
    self._checkFileCompatibility()
  File "/Users/agnor/.virtualenvs/tmp-5cfd6e743e152dc4/lib/python2.7/site-packages/pbcore-1.0.0-py2.7.egg/pbcore/io/align/BamIO.py", line 161, in _checkFileCompatibility
    "(only PacBio BAM files version >= 3.0b3 are supported)")
pbcore.io.align._BamSupport.IncompatibleFile: This BAM file is incompatible with this API (only PacBio BAM files version >= 3.0b3 are supported)
```

```
$ pip freeze
Cython==0.22
h5py==2.5.0
numpy==1.9.2
pbcore==1.0.0
pysam==0.8.1
six==1.9.0
wsgiref==0.1.2
```

**Comment by dalexander** [comment]
pbcore master doesn't work with 2.3-generated files because the file format spec has evolved.  You can use the tag "2.3-bam"

**Comment by arkyl** [comment]
Hi,
I had a similar problem. I used pbalign to generate a sam file and used samtools to convert sam to bam and sort. But when I run quiver on the bam it said "(only PacBio BAM files version >= 3.0b3 are supported)". Now I am stuck and any help would be really appreciated.

Yue

**Comment by dalexander** [comment]
Again, use the pbcore 2.3-bam tag if you want to use these old BAM files.

**Comment by dalexander** [comment]
But regarding the samtools sort issue--- SAMTools doesn't respect our version header.  Bamtools is a better choice.

https://github.com/PacificBiosciences/PacBioFileFormats/wiki/BAM-recipes

**Comment by arkyl** [comment]
Thanks a lot for the quick reply. That is my question, how to use the pbcore "2.3-bam" tag? Add it to the bam header?  I am running pbalign and quiver through command line.

**Comment by dalexander** [comment]
No, I was referring to downloading the git tag `2.3-bam` if you want to use pbcore from github.

If you have a smrtanalysis 2.3 installation, just use that.

**Comment by arkyl** [comment]
Hi,
I installed SMRTanalysis v2.3.0. And pbalign to generate sam, samtools to bam and bamtools to sort, and then run quiver. The quiver from v2.3.0 had the following error message:

[WARNING] 'fancyChunking' not yet available for BAM, disabling
Traceback (most recent call last):
  File "/stornext/snfs4/gen-asm/local-bin/smrtanalysis/current/analysis/bin/variantCaller.py", line 5, in <module>
    sys.exit(main())
  File "/stornext/snfs4/gen-asm/local-bin/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/GenomicConsensus/main.py", line 367, in main
    return tr.main()
  File "/stornext/snfs4/gen-asm/local-bin/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/GenomicConsensus/main.py", line 278, in main
    with BamReader(options.inputFilename) as peekCmpH5:
  File "/stornext/snfs4/gen-asm/local-bin/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/GenomicConsensus/io/BamIO.py", line 100, in __init__
    self._loadReadGroupInfo()
  File "/stornext/snfs4/gen-asm/local-bin/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/GenomicConsensus/io/BamIO.py", line 59, in _loadReadGroupInfo
    triple = ds["BINDINGKIT"], ds["SEQUENCINGKIT"], ds["SOFTWAREVERSION"]
KeyError: 'BINDINGKIT'

#version info from v2.3.0
quiver --version
  GenomicConsensus version: 0.9.2
  ConsensusCore version: 0.8.8
  h5py version: 2.2.0
  hdf5 version: 1.8.12

pbalign --version
pbalign 0.2.0.138342

blasr -version
blasr   1.3.1.142244


Next, I installed the newest quiver 1.1.0. And rerun quiver. It gave the previous error message:
 "(only PacBio BAM files version >= 3.0b7 are supported)")
pbcore.io.align._BamSupport.IncompatibleFile: This BAM file is incompatible with this API (only PacBio BAM files version >= 3.0b7 are supported)

So I am guessing that the problem is that the pbalign/blasr in v2.3.0 is not up to date so that the bam is not compatible? Unfortunately, I had problem installing the newest blasr that requires gcc >=4.7, which I had no authority to build.


My original intention to use bam instead of cmp.h5 files is that I am working on a large genome and find "cmph5tools.py merge" step is extremely slow. I am hoping that merging bams would be much faster. Now I find a new feature from quiver with v1.1.0; it can directly take fofn. And now I am running quiver with 200Gb of cmp.h5 files on a large genome, directly taking the fofn of cmp.h5 files. Any advice on this?  Thanks a lot.


Yue

**Comment by dalexander** [comment]
In pbalign from 2.3.0 you need to run with the option `--forquiver`

**Comment by arkyl** [comment]
If I use --forQuiever, it requires the output to be cmp.h5.

 [ERROR] The output file is not in cmp.h5 format, , while --forQuiver is true.

I am hoping to get output in bam format so that the merging step of bam files for large genome would be fast; hopefully much faster than merging cmp.h5 files.

**Comment by dalexander** [comment]
Ah, interesting.   I was not aware of that problem.  Can you share with me the result of `samtools view -H aligned_reads.bam` ?

**Comment by arkyl** [comment]
The following is the bam header. I used reads fasta as input for pbalign to generate sam without the --forQuiver. If I used reads .bas.h5 as input to generate sam, it had the same complaint: "ERROR] The output file is not in cmp.h5 format, , while --forQuiver is true." 

@HD     VN:1.3.1        SO:coordinate
@SQ     SN:scf7180000000002     LN:4634504      M5:d431a6e70cf9795dcaa8b8b5a0fd9d50
@RG     ID:d0e28133e2   DS:READTYPE=UNKNOWN     PU:/stornext/snfs4/gen-asm/local-bin/wgs-8.3rc1/Ecoli_example_P5C3/selfSampleData/K12/9-terminator/SRR1284073.fastq.100000.fa        SM:NO_CHIP_ID
@PG     ID:BLASR        CL:blasr /stornext/snfs4/gen-asm/local-bin/wgs-8.3rc1/Ecoli_example_P5C3/selfSampleData/K12/9-terminator/SRR1284073.fastq.100000.fa /stornext/snfs4/gen-asm/local-bin/wgs-8.3rc1/Ecoli_example_P5C3/selfSampleData/K12/9-terminator/asm.scf.fasta -sam -out /space1/tmp/13167033.sug-moab/tmpSrFI9a/JrpPRo.sam -bestn 10 -minMatch 12 -nproc 8 -minSubreadLength 50 -minReadLength 50 -randomSeed 1 -placeRepeatsRandomly -clipping soft       VN:1.3.1.142244
@PG     ID:SAMFILTER    CL:samFilter samFilter /space1/tmp/13167033.sug-moab/tmpSrFI9a/JrpPRo.sam /stornext/snfs4/gen-asm/local-bin/wgs-8.3rc1/Ecoli_example_P5C3/selfSampleData/K12/9-terminator/asm.scf.fasta /space1/tmp/13167033.sug-moab/tmpSrFI9a/7s4tBg.sam -minPctSimilarity 70 -minAccuracy 70 -minLength 50 -seed 1 -scoreSign -1 -hitPolicy randombest         VN:v0.1.0.134995

**Comment by dalexander** [comment]
Ah. I think I know the problem.  In the 2.3 BAM resequencing protocol, you need to use a tool called
`createChemistryHeader.py` to put the chem information into the BAM file (actually it generates a new SAM header, and then you need to use `samtools reheader` to produce a new BAM file that has it).

If you want to see more info on how to use it, look for the file `P_BAMMapping.py` in your smrtanalysis distribution.

I apologize, BAM support in 2.3 is a total hack.  It is going to be much better supported in 3.0.

**Comment by arkyl** [comment]
Thanks much. I will give that a try. 

I am actually more curious about my quiver test directly on a fofn of many cmp.h5 files with a total size of 200G. This is a test for large genome. If it can finish within a reasonable time, I would be glad to use that process and skip the whole merge/sort step. Not surprisingly, it is stilling running on the machine without result. I am using 14 cpus and 200G mem. Would you mind share your comments on this? Has quiver fofn been tried on a large genome? Thanks.

**Comment by dalexander** [comment]
We have tested a lot using the 3.0 pipeline and FOFNs of 3.0 BAM files---no real testing on that using 2.3 files or software, sorry.

**Comment by arkyl** [comment]
Thanks.

**Comment by arkyl** [comment]
Hi,

Sorry to ask about quiver again. We merged and sorted the cmp.h5 files for
a large genome using cmph5tools.py (following the steps as in
https://github.com/PacificBiosciences/pbalign/wiki/Tutorial:-How-to-divide-and-conquer-large-datasets-using-pbalign)
. The merge step took >2 weeks and sort step took within a day. We then
gave the sort cmp.h5 file to quiver but very quickly got the following
error:

Traceback (most recent call last):
  File
"/stornext/snfs4/gen-asm/local-bin/smrtanalysis/current/analysis/bin/variantCaller.py",
line 5, in <module>
    sys.exit(main())
  File
"/stornext/snfs4/gen-asm/local-bin/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/GenomicConsensus/main.py",
line 367, in main
    return tr.main()
  File
"/stornext/snfs4/gen-asm/local-bin/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/GenomicConsensus/main.py",
line 291, in main
    with CmpH5Reader(options.inputFilename) as peekCmpH5:
  File
"/stornext/snfs4/gen-asm/local-bin/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbcore/io/CmpH5IO.py",
line 767, in __init__
    rawAlignmentIndex = self.file["/AlnInfo/AlnIndex"].value
  File
"/stornext/snfs4/gen-asm/local-bin/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/h5py/_hl/dataset.py",
line 176, in value
    return self[()]
  File
"/stornext/snfs4/gen-asm/local-bin/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/h5py/_hl/dataset.py",
line 439, in __getitem__
    self.id.read(mspace, fspace, arr, mtype)
  File "h5d.pyx", line 179, in h5py.h5d.DatasetID.read (h5py/h5d.c:2479)
  File "_proxy.pyx", line 118, in h5py._proxy.dset_rw (h5py/_proxy.c:1300)
  File "_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
(h5py/_proxy.c:1051)
IOError: can't read data (Dataset: Read failed)


I think the quiver (from smrt v2.3)  itself should be ok as I tested it on
a ecoli data set and it is running . But for this large data set if you can
share your thought about the potential problems that caused the error, or
in addition what is the current strategy to quiver a large genome,  it
would be much appreciated.


Thanks,
Yue

**Comment by dalexander** [comment]
@PacificBiosciences/techsupport 

Yue, your cmp.h5 file is broken, apparently.  Tech support can take a look.

Proper support for large genomes is forthcoming in 3.0.  For now, I don't know what to tell you.  You seem quite patient so I imagine if you can get the cmp.h5 fixed you can push it through quiver.  

In the future please open a separate github issue for a new problem

**Comment by dalexander** [comment]
Yue-- another comment.  BAM resequencing protocol is intended for use for large genomes.  I guess you gave up on that and went back to cmp.h5?

**Comment by arkyl** [comment]
Again, thanks for the quick reply. I used pbalign to generate the cmp.h5 files. The same pbalign/quiver works fine for ecoli but for a large genome after merge/sort using cmph5tools.py (which didn't give any error), it didn't work. I guess the problem lied in the process of merge/sort cmp.h5 files. But anyway, I think I would give up on the cmp.h5 files and begin to test on the bam files. 
I am not quite in a hurry as we are testing 20x of pacbio data. The final data would be 50x in the future.

**Comment by dalexander** [comment]
My recommendation would be to build jobs from SMRTportal as opposed to trying to piece them together by hand on the commandline.  In this case, you can create a BAM resequencing job directly from SMRTportal.

**Comment by arkyl** [comment]
Thanks for the suggestions. I will keep that in mind. 
We preferred to tune assembly process by ourself and switch between big memory machine and clusters for speed. We also would like to use some software not in SMRTanalysis. I think we got all the process under control except for the final quiver polishing step. I admit it's a bit frustrating as the concept is straightforward. But thanks a lot for all your advices.
