### ISSUE TITLE
how to generate bam.pbi (PacBio BAM index)?

### ISSUE THREAD

**Issue by roncanepa** [PacificBiosciences/pbcore#14]
in the pbcore docs, I've seen references to readers that require a "bam.pbi (PacBio BAM index)".

But how do I create this?  I see nothing in the docs and I'm assuming this is different than the usual bam.bai index file.

Thank you.

**Comment by dalexander** [comment]
Hi, there is a tool "makePbi.py" provided in GenomicConsensus

**Comment by dbrowneup** [comment]
I've found that if you are using a pitchfork deployment of BLASR/GenomicConsensus, that there is a tool available called `pbindex` that will generate the .pbi

```
Usage: pbindex <input>

pbindex creates a index file that enables random-access to PacBio-specific data
in BAM files. Generated index filename will be the same as input BAM plus .pbi suffix.

Options:
  -h, --help            show this help message and exit
  --version             show program's version number and exit

  Input/Output:
    input               Input BAM file
```

**Comment by VDaric** [comment]
You can use pbindex  tool

SMRTLink/SMRTLink-v13.1/smrtlink/smrtcmds/bin/pbindex

**Comment by armintoepfer** [comment]
Are you commenting on a topic that has been closed six years ago...
