### ISSUE TITLE
Replace IndexedFastaReader with pyfaidx.Fasta

### ISSUE THREAD

**Issue by mdshw5** [PacificBiosciences/pbcore#19]
It looks like the interface to [IndexedFastaReader](https://github.com/PacificBiosciences/pbcore/blob/70e05f92fc68f69a450d313502931c9e944b8e29/pbcore/io/FastaIO.py#L392) is similar to [pyfaidx](http://github.com/mdshw5/pyfaidx) and that [one of your tools](http://github.com/PacificBiosciences/targeted-phasing-consensus) already uses pyfaidx for indexing. There are a few advantages to using the pyfaidx codebase:

- It's pretty well tested, with good test coverage (which you can freely improve on)
- I've implemented index creation and validation so you don't have to require users to have samtools
- The API is nicer (though that's subjective)

Would there be some interest in this?

**Comment by dalexander** [comment]
Nope

**Comment by dalexander** [comment]
Sorry, not interested in this at this time.
