### ISSUE TITLE
Test failures on Debian

### ISSUE THREAD

**Issue by afif-elghraoui** [PacificBiosciences/pbcore#21]
I'm updating the pbcore Debian package to your latest release, but two of the build-time tests are failing:

======================================================================
FAIL: test_create_cli (test_pbdataset.TestDataSet)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/«BUILDDIR»/python-pbcore-1.2.3+dfsg/tests/test_pbdataset.py", line 103, in test_create_cli
    self.assertEqual(r, 0)
AssertionError: 127 != 0
-------------------- >> begin captured logging << --------------------
test_pbdataset: DEBUG: Absolute
test_pbdataset: DEBUG: dataset.py create --type AlignmentSet /tmp/tmpTG7Mv1dataset-unittest/pbalchemysim.alignmentset.xml /«BUILDDIR»/python-pbcore-1.2.3+dfsg/pbcore/data/datasets/pbalchemysim0.alignmentset.xml /«BUILDDIR»/python-pbcore-1.2.3+dfsg/pbcore/data/datasets/pbalchemysim1.alignmentset.xml
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_split_cli (test_pbdataset.TestDataSet)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/«BUILDDIR»/python-pbcore-1.2.3+dfsg/tests/test_pbdataset.py", line 89, in test_split_cli
    self.assertEqual(r, 0)
AssertionError: 127 != 0
-------------------- >> begin captured logging << --------------------
test_pbdataset: DEBUG: dataset.py split --outdir /tmp/tmpePANm1dataset-unittest --contigs --chunks 2 /«BUILDDIR»/python-pbcore-1.2.3+dfsg/pbcore/data/datasets/pbalchemysim0.alignmentset.xml
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 241 tests in 32.003s

FAILED (failures=2, skipped=8)
----------------------------------------------------------------------

The versions of dependencies in use are:
pysam 0.8.3
h5py 2.5.0
numpy 1.9.2

Do you know what could be going on here?

Github doesn't seem to have a way of attaching log files, but I can provide the full build log if you tell me where to send it.

**Comment by dalexander** [comment]
@mdsmith, any idea?

**Comment by mdsmith** [comment]
I can reproduce this error by deleting the dataset.py executable script (specified in setup.py) from my $PATH, and recover from it by rerunning 'python setup.py install' on pbcore. This leads me to believe that dataset.py isn't being installed to a $PATH accessible directory before testing. One solution is to skip those tests if dataset.py isn't found in $PATH. I'm not sure what the best course of action is in the context of testing a debian package at build time.

**Comment by afif-elghraoui** [comment]
I see. What I had done is configure the nosetests to run using `python setup.py test`
That gets rid of `PYTHONPATH` issues, but I didn't expect to have this problem since the scripts are declared in setup.py.

I'll try setting the `PATH` at build time to include bin/ later today. Thanks for looking into this.

**Comment by mpkocher** [comment]
Martin, if the entry point was within the package (and therefore importable), you could call it via python -m pbcore.entrypoint.pbdataset style. This might help but it would also be somewhat sidestepping the purpose of the integration test. 

Alternatively, you could add @unittests.skipif(which("pbdataset.py") is None) model to handle the cases where make install isn't called before the tests are run.

**Comment by afif-elghraoui** [comment]
I should mention that adding that script's folder to the `PATH` during the build process didn't fix the problem. The assertion error in the two failed cases was slightly different, though. Instead of `127 != 0` as above, I got `1 != 0`.
I can skip those two tests during the build process, but for after installation, I have not been packaging the scripts `.open` and `dataset.py` into /usr/bin because the names are too vague for a system-wide installation. If they are intended to be on the user's path, would you mind renaming them to something more specific?

`pbdataset` (without the language extension) would be a nice subsitute for `dataset.py`. A similar renaming for `.open` would be welcome.

**Comment by dalexander** [comment]
I don't think there was ever an intention for pbcore to be installed system-wide on a linux sytem, we mainly operate out of virtualenvs or in a controlled environment.

**Comment by mdsmith** [comment]
It sounds like the best course of action is to disable those tests when dataset.py isn't found via @unittests.skipif(which("dataset.py") is None). I will submit a pull request to do so tomorrow if no one gets to it first.

**Comment by afif-elghraoui** [comment]
I've made that change in the uploaded package. I can confirm that the these two tests pass with the package as installed. The patch I created is at
https://anonscm.debian.org/cgit/debian-med/python-pbcore.git/tree/debian/patches/skip-integration-tests.patch
