### ISSUE TITLE
BamAlignment class feature transparency

### ISSUE THREAD

**Issue by knyquist** [PacificBiosciences/pbcore#22]
Make available class-features easy to find.

The availability of some object-instance features are hidden from the user unless they dive into the source. Attached is an example of accessing IPDs from a BamAlignment instance through pbcore…you can’t see that IPDs are available via dir(), but you can when you look at the BamAlignment class in the source code. 

One possibility, write a builtin dir-type class def that lists all features. Or figure out how to include all features within a call to python's builtin dir().

Toy .ipnb example located at Q:\Labs\Kristofor\analyses\pbcore_BAM_toy.html (pdf attached)
[pbcore_BAM_toy.pdf](https://github.com/PacificBiosciences/pbcore/files/34476/pbcore_BAM_toy.pdf)

**Comment by dalexander** [comment]
This is great Kris.  Could you give a specific example here---a snippet--where you expect better tab completion?

**Comment by dalexander** [comment]
This should be fixed now... next release will have the fix
