### ISSUE TITLE
Pin pysam to specific version to 0.8.1

### ISSUE THREAD

**Issue by mpkocher** [PacificBiosciences/pbcore#24]
https://github.com/pysam-developers/pysam/releases

This library is floating around a bit too much. The changes in 0.8.4 break compatibility with pbcore.

https://circleci.com/gh/PacificBiosciences/pbcore/98

**Comment by dalexander** [comment]
Oh wow, did they finally release 0.8.4?  I can pin it to 0.8.3

**Comment by dalexander** [comment]
... or make it work with 0.8.4
