### ISSUE TITLE
Add createdAt accessor to DataSet

### ISSUE THREAD

**Issue by mpkocher** [PacificBiosciences/pbcore#31]

**Comment by mpkocher** [comment]
Fyi, Herb should be adding iso8601 python package to the build which can be used to parse the created at field. This should simplify the conversion to datetime obj.

http://bugzilla.nanofluidics.com/show_bug.cgi?id=30186

**Comment by dalexander** [comment]
Not interested in adding additional dependencies to pbcore for minor features

**Comment by mdsmith** [comment]
Resolved by pull request #45
