### ISSUE TITLE
add ".open" support for datasets (XML)

### ISSUE THREAD

**Issue by dalexander** [PacificBiosciences/pbcore#37]
@mdsmith, I need this "yesterday"....

**Comment by mdsmith** [comment]
This has been in there for a month, and works for me. What error message is it giving you?

**Comment by dalexander** [comment]
I will try again.

**Comment by dalexander** [comment]
OK, my fault for running an outdated pbcore.  And I was not aware you had already implemented this.

You are an amazing engineer, you actually went back and implemented it "yesterday".  Impressive.

**Comment by dalexander** [comment]
I'm going to release 1.2.7
