### ISSUE TITLE
hdf5.h missing h5py fails to install

### ISSUE THREAD

**Issue by adeslatt** [PacificBiosciences/pbcore#5]
Following the directions for install:
In file included from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1760:0,

```
             from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:17,

             from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,

             from h5py/api_compat.h:21,

             from h5py/defs.c:259:
```

/usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]

In file included from h5py/defs.c:259:0:

h5py/api_compat.h:22:18: fatal error: hdf5.h: No such file or directory

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

---

  Can't roll back h5py; was not uninstalled
Command /mnt/myenv2/bin/python -c "import setuptools;**file**='/mnt/myenv2/build/h5py/setup.py';exec(compile(open(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-pf_SBW-record/install-record.txt --single-version-externally-managed --install-headers /mnt/myenv2/include/site/python2.7 failed with error code 1 in /mnt/myenv2/build/h5py
Storing complete log in /home/ubuntu/.pip/pip.log

**Comment by adeslatt** [comment]
update 3/1/2015 (wow -- exactly one year later-- kind of freaky!)

had to do the same thing again but versions change in a year.
wget http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.14.tar
and
export HDF5_DIR=/mnt/hdf5-1.8.14/hdf5
pip install tables
and again...  this worked.

**Comment by pengchy** [comment]
Thank you adeslatt, this information is very useful!

**Comment by marcocamma** [comment]
on Debian stable (8.1)

export HDF5_DIR=/usr/lib/x86_64-linux-gnu/hdf5/serial/
pip install h5py
hope it helps,
marco

**Comment by dalupus** [comment]
On ubuntu 16.0.4
sudo apt-get install libhdf5-serial-dev hdf5-tools
pip install h5py

**Comment by yuezhao-UT** [comment]
@dalupus Thanks! This fixes my problem on Ubuntu 14.04.

**Comment by ZhaoDingfan** [comment]
@dalupus Thanks a lot! It really saved me, I'm stuck in this problem for several hours without having any clues. This fixes my problem on Raspberry with Raspian system.

**Comment by auranprost** [comment]
Same issue here.  Here's information on what I am running and how I solved it

**OS:** CentOS 7
**Python Version:** 3.6.0 in a virtualenv

yum update
yum install -y hdf5*
pip install six
pip install numpy
pip install Cython
pip install h5py
