### ISSUE TITLE
Deprecating the h5py dependency

### ISSUE THREAD

**Issue by natechols** [PacificBiosciences/pbcore#62]
As a first step towards moving away from this altogether, would it be possible to make the dependency optional so that pbcore can be installed without hdf5 support?  Removing the automatic h5py installation would not prevent us from continuing to support it in pbcore (or smrtanalysis) indefinitely, but it is unnecessary for many of our standalone internal use cases (e.g. pbcommand testing) and the extra overhead makes them considerably more complicated to set up.

**Comment by dalexander** [comment]
It's too soon.

**Comment by dalexander** [comment]
Let me comment on this: SA 3.0 isn't even available for download yet.  Think about that.  I'm not dropping  H5 support until at least a year after SA 3.0 is generally available.
