### ISSUE TITLE
Trouble building this with anaconda

### ISSUE THREAD

**Issue by govinda-kamath** [PacificBiosciences/pbcore#76]
On trying to build this with anaconda, I seem to get an error message saying that need pysam >=0.8.4. I do have the pysam 0.8.4 on my machine. I'd appreciate any help with this.

After running 

> conda skeleton pypi pbcore

I get the following error while running

> conda build pbcore

<img width="392" alt="screen shot 2016-03-09 at 12 37 58 pm" src="https://cloud.githubusercontent.com/assets/7320464/13649721/d6c767fc-e5f3-11e5-84d2-2f1c81dcc2a5.png">

I do have pysam 0.8.4 in my conda list

Thanks,
Govinda.

**Comment by dalexander** [comment]
Sorry, no idea.  Take it up with the conda people.

**Comment by mhsieh** [comment]
By the way, I don't have pysam newer than 0.6 in my miniconda, version 0.9 or anything newer than 0.8.4 also are not on the list of anaconda - https://docs.continuum.io/anaconda/pkg-docs .

**Comment by mhsieh** [comment]
Works with this:
```
conda skeleton pypi pysam
conda build --no-test pysam
conda skeleton pypi pbcore
conda build --no-test pbcore
```

**Comment by govinda-kamath** [comment]
That works! Thanks a lot!!

**Comment by mhsieh** [comment]
you should still ask conda people to upgrade the pysam in the repository
