### ISSUE TITLE
quiver complaints bam files generated by blasr

### ISSUE THREAD

**Issue by JeanQin** [PacificBiosciences/pbcore#81]
I'm trying to use quiver to polish contigs assembled by falcon. I aligned *bax.h5 reads to the contigs to create sam file and use samtools to convert sam to bam and then use the *bam file as input for quiver. The run failed immediately with error: IOError: Invalid or nonexistent cmp.h5 file. I was told that old quiver requires cmp.h5 as its input file but new quiver should accept bam files as its input files. Is it correct? Our smrtanalysis is smrtanalysis-2.3.0.140936. Any suggestion would be greatly appreciated.

**Comment by dalexander** [comment]
See: https://github.com/PacificBiosciences/PacBioFileFormats/wiki/BAM-recipes

You need to use SMRTanalysis 3.0 to generate BAM files adhering to our specification.  Unfortunately SMRTanalysis 3.0 is not generally available yet, so you'd best stick to the `cmp.h5` path for now.

**Comment by JeanQin** [comment]
Thank you so much for your quick suggestion. I read threads about cmp.h5 approach. It seems to me that people has been struggling to get it to work using command line for large genome. It takes very long to generate cmp.h5 file (e.g., 2 weeks) and get error with cmp.h5. Is it true and any suggestion before getting started?

**Comment by dalexander** [comment]
Yes, people have struggled with attempting to run resequencing by themselves, because they try to generate an enormous cmp.h5 file and then run a monster quiver job to process it.

That's the wrong approach--they (and you) should use smrtpipe (or smrtportal), which have built-in intelligence for splitting up jobs into smaller pieces that get farmed out on the cluster. 

The story gets even better in SMRTanalysis 3.0, where we've thought a bit harder about how to divide up tasks for cluster scheduling.

**Comment by JeanQin** [comment]
Thanks, David for your suggestion. It makes sense to use smrtpipe or smrtportal. Unfortunately, falcon is not part of smrtpipe or portal. We use falcon since we have high heterogeneous genome. We have to run quiver to polish the falcon contigs. The genome is 100MB. I just aligned all raw reads against the falcon contigs to generate 12 cmp.h5 files (3 per smrt cells), However, we I run quiver, I got the same error: IOError: Invalid or nonexistent cmp.h5 file, aligned_reads.fofn.  aligned_reads.fofn contains a list of cmp.h5 file name. Any clue?

**Comment by dalexander** [comment]
quiver in 2.3 SMRTanalysis doesn't support "fofn" files, it can only operate on a single cmp.h5 file.  This is on of the improvments in 3.0.

**Comment by JeanQin** [comment]
What do you suggest with multiple cmp.h5 files using quiver?

**Comment by dalexander** [comment]
You can use a quiver from Github, install it in an isolated virtualenv

**Comment by JeanQin** [comment]
Thanks. Are you saying that the standalone quiver from Github is a newer version which can accepts "fofn"? Will it accept the alignment files (cmp.h5 or bam) generated by smrt 2.3?

**Comment by dalexander** [comment]
Yes

**Comment by JeanQin** [comment]
Thanks, David. We'll give it a try
