### ISSUE TITLE
Install Quiver

### ISSUE THREAD

**Issue by JeanQin** [PacificBiosciences/pbcore#82]
We're told to install quiver from github in order to use .fofn for multiple bam files.

I found this online document that mentions about some environment variables need to be different from the rest of the package. It also has extra instructions that are probably going to corrupt the present installation if we followed them. Could you let us know what're the some environment variables need to be different from the rest of the package? We can use the module control to manage different environments.

/tools/bioinfo/app/smrtanalysis-2.3.0.140936/install/smrtanalysis_2.3.0.140936/analysis/lib/python2.7/GenomicConsensus/quiver

Thanks,
Jean

**Comment by dalexander** [comment]
If this issue is related to installing GenomicConsensus, please open an issue there.
