### ISSUE TITLE
pbcore.io.merge_gffs_sorted should clean up after itself

### ISSUE THREAD

**Issue by nlhepler** [PacificBiosciences/pbcore#97]
but it doesn't. closing PacificBiosciences/pbcoretools#84.

**Comment by nlhepler** [comment]
Ahh, there's merge_gffs_sorted. But this should use NamedTemporaryFile properly (e.g. with a `with` statement) to clean up after itself.

**Comment by natechols** [comment]
I don't think a with statement will work for this, but try/finally will.

**Comment by natechols** [comment]
Fixed by commit 9e79663
